# Generated by Django 4.1.7 on 2023-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_eminities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Eminities',
            field=models.ManyToManyField(to='home.eminities'),
        ),
    ]
